-- WHERE y HAVING --

-- Contar los Cursos que aún no comenzaron --

SELECT  NOMBRE NOMBRE_CURSO, MODALIDAD, COUNT(*) N_MODALIDAD
FROM    MATERIAS
        INNER JOIN CURSOS
          ON CURSOS.ID_MATERIA = MATERIAS.ID_MATERIA
WHERE FEC_INICIO > SYSDATE
GROUP BY NOMBRE, MODALIDAD
ORDER BY 1,2
;

-- HAVING: Grupos con cantidad mayor que 1 --

SELECT  NOMBRE NOMBRE_CURSO, MODALIDAD, COUNT(*) N_MODALIDAD
FROM    MATERIAS
        INNER JOIN CURSOS
          ON CURSOS.ID_MATERIA = MATERIAS.ID_MATERIA
WHERE FEC_INICIO > SYSDATE
GROUP BY NOMBRE, MODALIDAD
HAVING COUNT(*) > 1
ORDER BY 1,2
;
