SELECT PAISES.NOMBRE PAIS, PAISES.ID_PAIS "CODIGO",
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.FEC_NAC "FECHA NACIMIENTO"
FROM PERSONAS
INNER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
ORDER BY 1;

SELECT 
DOCENTES.FEC_INGRESO "INGRESÓ",
DOCENTES.FEC_REGISTRO "REGISTRO",
DOCENTES.FEC_EGRESO "EGRESA EN...",
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.TELEFONO
FROM PERSONAS
INNER JOIN DOCENTES
ON DOCENTES.ID_PERSONA = PERSONAS.ID_PERSONA
ORDER BY 1;

SELECT
PAISES.ID_PAIS "CODIGO DE PAIS", PAISES.NOMBRE "PAIS",
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.FEC_NAC,
PERSONAS.CORREO "MAIL"
FROM PERSONAS
INNER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
ORDER BY 1;

SELECT 
PAISES.NOMBRE AS "PROCEDENCIA",
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.CORREO "CONTACTO"
FROM PERSONAS
INNER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
ORDER BY 1;

SELECT
DOCENTES.FEC_INGRESO "INGRESÓ", DOCENTES.FEC_REGISTRO "SE REGISTRÓ",
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.FEC_NAC "FECHA NACIMIENTO"
FROM PERSONAS
INNER JOIN DOCENTES
ON DOCENTES.ID_PERSONA = PERSONAS.ID_PERSONA
ORDER BY 1
;

SELECT --Con muchas combinaciones
PERSONAS.NOMBRE,
PERSONAS.APELLIDO
FROM PERSONAS
INNER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
WHERE PAISES.NOMBRE = 'URUGUAY'
OR
(
(PAISES.NOMBRE = 'RUSIA' AND PERSONAS.NOMBRE = 'NATASHA')
OR
(PAISES.NOMBRE = 'ESTADOS UNIDOS' AND PERSONAS.NOMBRE = 'THOMAS')
OR
(PAISES.NOMBRE = 'ESTADOS UNIDOS' OR PERSONAS.APELLIDO = 'WALLACE')
)
;

SELECT --Con muchas más combinaciones
PAISES.NOMBRE "PROCEDENCIA",
PERSONAS.APELLIDO,
PERSONAS.NOMBRE,
PERSONAS.CORREO
FROM PERSONAS
INNER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
WHERE PAISES.NOMBRE = 'RUSIA'
OR
  (
  (PERSONAS.NOMBRE = 'THOMAS' AND PAISES.NOMBRE = 'ESTADOS UNIDOS')
    OR
  (PERSONAS.APELLIDO = 'HERNÁNDEZ' AND PAISES.NOMBRE = 'URUGUAY')
  )
OR
  (
  (PAISES.ID_PAIS = 9 AND PERSONAS.NOMBRE = 'JOSNIAK')
    AND
  (PERSONAS.APELLIDO = 'KLOGFGRANK')
  )

ORDER BY 1
;

SELECT 
  PAISES.NOMBRE, 
  PAISES.ID_PAIS "COD. PAIS",
  PERSONAS.APELLIDO,
  PERSONAS.NOMBRE,
  PERSONAS.TELEFONO,
  PERSONAS.DOCUMENTO
FROM PERSONAS
  INNER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
  WHERE PAISES.NOMBRE = 'URUGUAY'
OR
  PERSONAS.APELLIDO = 'HERNÁNDEZ'
ORDER BY 3;