SELECT
ESTUDIANTES.ID_ESTUDIANTE "Estudiante #",
MATERIAS.NOMBRE Materia,
MATERIAS.ID_MATERIA,
CURSOS.ID_CURSO "Curso #",
CURSOS.FEC_INICIO ||' - '|| CURSOS.FEC_FIN "Inicia-Termina",
MATRICULAS.FEC_MATRICULA "Fecha de Matrícula",
MATRICULAS.NOTA_FINAL "Calificación Final"
FROM MATRICULAS
INNER JOIN CURSOS ON CURSOS.ID_CURSO = MATRICULAS.ID_CURSO
INNER JOIN MATERIAS ON MATERIAS.ID_MATERIA = CURSOS.ID_MATERIA
INNER JOIN ESTUDIANTES ON MATRICULAS.ID_ESTUDIANTE = ESTUDIANTES.ID_ESTUDIANTE;


SELECT
ESTUDIANTES.ID_ESTUDIANTE,
PERSONAS.APELLIDO,
PERSONAS.NOMBRE,
PAISES.NOMBRE PAIS
FROM PERSONAS
INNER JOIN ESTUDIANTES
ON ESTUDIANTES.ID_PERSONA = PERSONAS.ID_PERSONA
INNER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
ORDER BY 3;




SELECT
ID_ESTUDIANTE "Estudiante Nro.",
  PERSONAS.APELLIDO||', '||PERSONAS.NOMBRE "Apellido, Nombre",
    PAISES.NOMBRE
FROM PERSONAS
  INNER JOIN ESTUDIANTES
  ON PERSONAS.ID_PERSONA = ESTUDIANTES.ID_PERSONA
    INNER JOIN PAISES
    ON PAISES.ID_PAIS = PERSONAS.ID_PAIS;


-- Nombre, apellido, id y País del docente qe dicta 'Literatura post-modernista'

SELECT 
  DOCENTES.ID_DOCENTE                         "Docente #",
  PERSONAS.APELLIDO ||', '|| PERSONAS.NOMBRE  "Apellido, Nombre",
  PAISES.NOMBRE                               "País de origen",
  --MATERIAS.NOMBRE                             "Dicta la Materia",
  MATRICULAS.FEC_MATRICULA                    "Fecha de Matricula"
FROM CURSOS
  INNER JOIN DOCENTES ON DOCENTES.ID_DOCENTE  = CURSOS.ID_DOCENTE
  INNER JOIN PERSONAS ON DOCENTES.ID_PERSONA  = PERSONAS.ID_PERSONA
  INNER JOIN PAISES   ON PAISES.ID_PAIS       = PERSONAS.ID_PAIS
  INNER JOIN MATERIAS ON MATERIAS.ID_MATERIA  = CURSOS.ID_MATERIA
  INNER JOIN MATRICULAS ON CURSOS.ID_CURSO    = MATRICULAS.ID_CURSO
  WHERE MATERIAS.NOMBRE LIKE 'LITERATURA%'
ORDER BY 1;


SELECT COUNT (ID_PERSONA) "CANTIDAD DE REGISTROS" FROM PERSONAS;

SELECT NOMBRE, APELLIDO
FROM PERSONAS
WHERE ID_PERSONA NOT IN
(SELECT ESTUDIANTES.ID_PERSONA FROM ESTUDIANTES);

SELECT APELLIDO ||', '||NOMBRE "Estudiante", ID_PERSONA
FROM PERSONAS
WHERE ID_PERSONA IN
(SELECT ESTUDIANTES.ID_PERSONA FROM ESTUDIANTES);



SELECT
--PERSONAS.NOMBRE,
CURSOS.MODALIDAD,
DOCENTES.ID_DOCENTE "Nro. DOCENTE"
FROM MATERIAS
--INNER JOIN PERSONAS ON DOCENTES.ID_PERSONA = PERSONAS.ID_PERSONA
INNER JOIN CURSOS ON CURSOS.ID_MATERIA = MATERIAS.ID_MATERIA
INNER JOIN DOCENTES ON DOCENTES.ID_DOCENTE = CURSOS.ID_DOCENTE
ORDER BY 1;


SELECT NOMBRE, APELLIDO
FROM PERSONAS
WHERE FEC_NAC IN
(
   SELECT
   FEC_NAC FROM 
   PERSONAS WHERE FEC_NAC > '01/01/1960'
);


SELECT  table_name,
        index_name,
        uniqueness
FROM user_indexes
ORDER BY 1,2;