SELECT
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PAISES.NOMBRE PAIS
FROM PERSONAS
LEFT OUTER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS ------------- LEFT Devuelve todos los de la izquierda aunque no tengan registrad PAIS
ORDER BY 2;

SELECT
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.FEC_NAC "FECHA NACIMIENTO",-------------- RIGHT Devuelve todos los de la derecha aunque no tengan Registrado Personas
PAISES.NOMBRE PAIS
FROM PERSONAS
RIGHT OUTER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
ORDER BY 1;


SELECT
PAISES.ID_PAIS CODIGO,
PAISES.NOMBRE PAIS,
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.FEC_NAC "NACIO EL"   -- FULL Devuelve todos: los paises que no tiene persona
FROM PERSONAS                 -- y las personas que no rienen pais.
FULL OUTER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
ORDER BY 1;

SELECT
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.CORREO,
PAISES.NOMBRE
FROM PERSONAS
FULL OUTER JOIN PAISES
ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
ORDER BY 4;


SELECT
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
DOCENTES.ID_DOCENTE "DOCENTE Nro."
FROM PERSONAS
RIGHT OUTER JOIN DOCENTES
ON DOCENTES.ID_PERSONA = PERSONAS.ID_PERSONA
ORDER BY 3;

SELECT
PERSONAS.APELLIDO,
PERSONAS.NOMBRE,
ESTUDIANTES.ID_ESTUDIANTE "ESTUDIANTE Nro.",
ESTUDIANTES.FEC_REGISTRO "REGISTRADO EL"
FROM PERSONAS
RIGHT OUTER JOIN ESTUDIANTES
ON ESTUDIANTES.ID_PERSONA = PERSONAS.ID_PERSONA
ORDER BY 3;

SELECT
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PAISES.NOMBRE PAIS,
DOCENTES.ID_DOCENTE "Nro. Doc",
CURSOS.ID_MATERIA
FROM DOCENTES
RIGHT OUTER JOIN CURSOS ON DOCENTES.ID_DOCENTE = CURSOS.ID_DOCENTE
RIGHT OUTER JOIN PERSONAS ON PERSONAS.ID_PERSONA = DOCENTES.ID_PERSONA
INNER JOIN PAISES ON PERSONAS.ID_PAIS = PAISES.ID_PAIS
;

SELECT
  CURSOS.ID_CURSO "ID. Curso",
  CURSOS.FEC_INICIO,
  CURSOS.FEC_FIN,
  CURSOS.MODALIDAD,
    PERSONAS.APELLIDO ||', '|| PERSONAS.NOMBRE "Nombre Completo",
    PERSONAS.CORREO "Mail",
      PAISES.NOMBRE Pais,
        MATERIAS.NOMBRE "Materia Dictada"
FROM DOCENTES
  INNER JOIN CURSOS ON CURSOS.ID_DOCENTE = DOCENTES.ID_DOCENTE
  INNER JOIN PERSONAS ON PERSONAS.ID_PERSONA = DOCENTES.ID_PERSONA
  INNER JOIN PAISES ON PERSONAS.ID_PAIS = PAISES.ID_PAIS
  INNER JOIN MATERIAS ON CURSOS.ID_MATERIA = MATERIAS.ID_MATERIA
  ORDER BY 2;


SELECT
  CURSOS.ID_CURSO "ID. Curso",
  CURSOS.FEC_INICIO,
  CURSOS.FEC_FIN,
  CURSOS.MODALIDAD,
    PERSONAS.APELLIDO ||', '|| PERSONAS.NOMBRE "Nombre Completo",
    PERSONAS.CORREO "Mail",
      PAISES.NOMBRE Pais,
        MATERIAS.NOMBRE "Materia Dictada"
FROM DOCENTES
  INNER JOIN CURSOS ON CURSOS.ID_DOCENTE = DOCENTES.ID_DOCENTE
  INNER JOIN PERSONAS ON PERSONAS.ID_PERSONA = DOCENTES.ID_PERSONA
  INNER JOIN PAISES ON PAISES.ID_PAIS = PERSONAS.ID_PAIS
  INNER JOIN MATERIAS ON MATERIAS.ID_MATERIA = CURSOS.ID_MATERIA
ORDER BY 8;

DESCRIBE MATRICULAS;



SELECT
PERSONAS.APELLIDO ||', '|| PERSONAS.NOMBRE "Nombre completo",
ESTUDIANTES.ID_ESTUDIANTE
FROM ESTUDIANTES
INNER JOIN PERSONAS
ON PERSONAS.ID_PERSONA = ESTUDIANTES.ID_PERSONA
order by 2
;


SELECT PERSONAS.APELLIDO||', '||PERSONAS.NOMBRE "Apellido, Nombre",
PAISES.NOMBRE,
ESTUDIANTES.ID_ESTUDIANTE
FROM PERSONAS
INNER JOIN ESTUDIANTES ON PERSONAS.ID_PERSONA = ESTUDIANTES.ID_PERSONA
INNER JOIN PAISES ON PERSONAS.ID_PAIS = PAISES.ID_PAIS;

SELECT
PERSONAS.APELLIDO||', '||PERSONAS.NOMBRE "Apellido, Nombre",
PAISES.NOMBRE,
ESTUDIANTES.ID_ESTUDIANTE
FROM ESTUDIANTES
INNER JOIN PERSONAS ON PERSONAS.ID_PERSONA = ESTUDIANTES.ID_PERSONA
INNER JOIN PAISES ON PERSONAS.ID_PAIS = PAISES.ID_PAIS;

DESCRIBE MATRICULAS;
