--||||||||||||||||||||||||||||||||||||||||||||||||||||||||
--||                      QUERYS                        ||
--||||||||||||||||||||||||||||||||||||||||||||||||||||||||


SELECT 
NOMBRE "País", ID_PAIS "Identificador" --Paises con ID impar
FROM PAISES
WHERE mod(ID_PAIS, 3) = 0
ORDER BY 2
;

SELECT 
NOMBRE "País", ID_PAIS "Identificador" --Paises con ID par
FROM PAISES
WHERE mod(ID_PAIS, 2) = 0
ORDER BY 2
;


SELECT NOMBRE "A", APELLIDO "B", CORREO
FROM 
PERSONAS;

SELECT NOMBRE, APELLIDO, CORREO
FROM PERSONAS
WHERE ID_PAIS = 12;

SELECT NOMBRE
FROM PAISES
WHERE ID_PAIS = 12;

SELECT NOMBRE "País", ID_PAIS "CÓDIGO"
FROM PAISES
order by 1;

SELECT NOMBRE, APELLIDO, CORREO, TELEFONO
FROM PERSONAS
WHERE SYSDATE - FEC_NAC > 18;


SELECT NOMBRE, APELLIDO
FROM PERSONAS
WHERE ID_PERSONA = 2;


DELETE FROM PERSONAS WHERE ID_PERSONA = 12;

SELECT * 
FROM PERSONAS
WHERE 
NOMBRE IN('%HOLA%');

SELECT * 
FROM  PERSONAS 
WHERE NOMBRE = 'MARTÍN' 
OR    APELLIDO IN ('HERNÁNDEZ', 'BELÉN')
OR    ID_PAIS  IN (1,2,10,17)
;

SELECT ID_PERSONA FROM PERSONAS WHERE NOMBRE = 'PAQUIRRÍN';
SELECT MAX(ID_DOCENTE)+1 FROM DOCENTES;

SELECT * FROM PERSONAS
ORDER BY ID_PERSONA DESC; --Ordena de forma DESCENDENTE

COMMIT;


SELECT NOMBRE, APELLIDO, FEC_NAC
FROM PERSONAS
WHERE FEC_NAC BETWEEN '01/01/1920' AND '31/10/1984'
ORDER BY 3;

SELECT ID_CURSO IDE, MODALIDAD, FEC_INICIO
FROM CURSOS
WHERE FEC_INICIO BETWEEN '01/01/2015' AND '01/01/2017';



SELECT
MATERIAS.NOMBRE MATERIA,
CURSOS.ID_CURSO,
CURSOS.MODALIDAD,
CURSOS.FEC_INICIO "INICIA EN"
FROM CURSOS
INNER JOIN MATERIAS
ON MATERIAS.ID_MATERIA = CURSOS.ID_MATERIA
ORDER BY 1, 3;


SELECT
ESTUDIANTES.FEC_REGISTRO "REGISTRADO EL",
PERSONAS.NOMBRE,
PERSONAS.APELLIDO,
PERSONAS.CORREO
FROM PERSONAS
INNER JOIN ESTUDIANTES
ON ESTUDIANTES.ID_PERSONA = PERSONAS.ID_PERSONA
WHERE FEC_REGISTRO BETWEEN '01/01/2015' AND '01/01/2016'
ORDER BY FEC_REGISTRO;



SELECT
CURSOS.FEC_INICIO,
CURSOS.FEC_FIN,
CURSOS.MODALIDAD,
MATERIAS.NOMBRE MATERIA
FROM CURSOS
FULL OUTER JOIN MATERIAS
ON MATERIAS.ID_MATERIA = CURSOS.ID_MATERIA
ORDER BY 1, 2;

SELECT
CURSOS.FEC_INICIO,
CURSOS.FEC_FIN,
CURSOS.MODALIDAD,
MATERIAS.NOMBRE MATERIA
FROM CURSOS
RIGHT OUTER JOIN MATERIAS
ON MATERIAS.ID_MATERIA = CURSOS.ID_MATERIA
ORDER BY 4;




INSERT INTO CONTINENTES
(ID_CONTINENTE, NOMBRE, ECONOMIA)
SELECT
MAX(ID_CONTINENTE)+1, 'PRUEBA1', 56
FROM CONTINENTES
;

INSERT INTO CONTINENTES
(ID_CONTINENTE, NOMBRE, ECONOMIA)
VALUES
(SEQ_ID_CONTINENTE.NEXTVAL, 'PRUEBA2',78)
;

INSERT INTO CONTINENTES
(ID_CONTINENTE, NOMBRE, ECONOMIA)
SELECT
MAX(ID_CONTINENTE)+1, 'PRUEBAX', 8999
FROM CONTINENTES
;

INSERT INTO CONTINENTES
(ID_CONTINENTE, NOMBRE, ECONOMIA)
SELECT
MAX(ID_CONTINENTE)+1, 'CCCCCCCCCCCCCCCCCC', 8999
FROM CONTINENTES
;

DELETE FROM CONTINENTES
WHERE ECONOMIA = 8999;

DELETE FROM CONTINENTES
WHERE ECONOMIA IN (56, 78);


SELECT *
FROM CONTINENTES;
SELECT * FROM PERSONAS;

DELETE FROM PERSONAS
WHERE FEC_NAC < '01/01/1900';

SELECT * FROM PERSONAS
WHERE FEC_NAC < '01/01/1980';


DESCRIBE PERSONAS;

SELECT SEQ_ID_CONTINENTE.NEXTVAL FROM CONTINENTES;



SELECT * FROM USER_SEQUENCES;