--.....--...--..||||||||||||||||||||||
--.....--...--..|| Crear SECUENCIAS ||
--.....--...--..||||||||||||||||||||||

SELECT MAX(ID_PAIS)
FROM PAISES;

CREATE SEQUENCE SEQ_ID_PAIS
START WITH 19
INCREMENT BY 1;

SELECT MAX(ID_DOCENTE)+1
FROM DOCENTES;

CREATE SEQUENCE SEQ_ID_DOCENTE
START WITH 7
INCREMENT BY 1;

SELECT MAX(ID_ESTUDIANTE)
FROM ESTUDIANTES;

CREATE SEQUENCE SEQ_ID_ESTUDIANTE
START WITH 4
INCREMENT BY 1;

SELECT MAX(ID_MATERIA)+1
FROM MATERIAS;

CREATE SEQUENCE SEQ_ID_MATERIA
START WITH 9
INCREMENT BY 1;

SELECT MAX(ID_CURSO)+1
FROM CURSOS;

CREATE SEQUENCE SEQ_ID_CURSO
START WITH 4
INCREMENT BY 1;